version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mdb/mdbdata/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: mwfdb

  app:
    build: .
    container_name: myapp
    restart: always
    ports:
      - "7383:7383"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongodb:27017/mwfdb
    volumes:
      - .:/usr/src/app

volumes:
  mongo-data:
    driver: local
